CREATE TABLE "GCG_4954_BFData"(
 "Order_No" CHAR(7) NOT NULL ,
 "BF_Status" VARCHAR(10),
 "BF_Intial_PressDrop" VARCHAR(20),
 "BF_Intial_OpenedAt" VARCHAR(20),
 "BF_Intial_RStatus" BIT NOT NULL ,
 "BF_Intial_DblCheck1" BIT NOT NULL ,
 "BF_Intial_DblTigLek" BIT NOT NULL ,
 "BF_Intial_DblTigLek2" BIT NOT NULL ,
 "BF_Intial_DblType1" VARCHAR(10),
 "BF_Intial_DblType2" VARCHAR(10),
 "BF_Intial_AirInlet" VARCHAR(10),
 "BF_Intial_CheckValue" VARCHAR(10),
 "BF_Intial_Opened" BIT NOT NULL ,
 "BF_Intial_PV_Status" BIT NOT NULL ,
 "BF_Intial_TestStatus" BIT NOT NULL ,
 "BF_Intial_TestDate" DATE,
 "BF_Intial_SystemPSI" VARCHAR(10),
 "BF_Intial_DeteMeter" VARCHAR(10),
 "BF_RepairNotes" LONGVARCHAR,
 "BF_Repair_PressDrop" VARCHAR(10),
 "BF_Repair_OpenedAt" VARCHAR(10),
 "BF_Repair_RStatus" BIT NOT NULL ,
 "BF_Repair_DblCheck1" BIT NOT NULL ,
 "BF_Repair_DblTight1" BIT NOT NULL ,
 "BF_Repair_DblTight2" BIT NOT NULL ,
 "BF_Repair_DblType1" VARCHAR(10),
 "BF_Repair_DblType2" VARCHAR(10),
 "BF_Repair_AirInlet" VARCHAR(10),
 "BF_Repair_CheckValue" VARCHAR(10),
 "BF_Repair_Opdfully" BIT NOT NULL ,
 "BF_Repair_TestStatus" BIT NOT NULL ,
 "BF_Repair_TestDate" VARCHAR(20),
 "BF_Serial" CHAR(20),
 "BF_Employee" CHAR(5),
 "BF_CalibrationDate" DATE,
 "BF_WaterRestored" BIT NOT NULL ,
 "BF_Close" BIT NOT NULL ,
 "Order_Line" CHAR(4) NOT NULL ,
 PRIMARY KEY ("Order_No", "Order_Line"));